--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/HyduseaMC/HyduseaSpawners
build-by-default: false
branches:
- master
projects:[] 
  HyduseaSpawners:
     path: ""
     icon: Pig_Spawner.png 
...
